//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "dm")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub u_name: Option<String>,
    pub u_id: Option<i64>,
    pub u_face: Option<String>,
    pub timestamp: Option<i64>,
    pub room_id: Option<i64>,
    pub msg: Option<String>,
    pub msg_id: Option<String>,
    pub guard_level: Option<i64>,
    pub fans_medal_wearing_status: Option<bool>,
    pub fans_medal_name: Option<String>,
    pub fans_medal_level: Option<i64>,
    pub emoji_img_url: Option<String>,
    pub dm_type: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
